require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mailers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Mailer. As you add validations to Mailer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Mailer.create! valid_attributes
      get mailers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mailer = Mailer.create! valid_attributes
      get mailer_url(mailer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mailer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mailer = Mailer.create! valid_attributes
      get edit_mailer_url(mailer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Mailer" do
        expect {
          post mailers_url, params: { mailer: valid_attributes }
        }.to change(Mailer, :count).by(1)
      end

      it "redirects to the created mailer" do
        post mailers_url, params: { mailer: valid_attributes }
        expect(response).to redirect_to(mailer_url(Mailer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Mailer" do
        expect {
          post mailers_url, params: { mailer: invalid_attributes }
        }.to change(Mailer, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mailers_url, params: { mailer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mailer" do
        mailer = Mailer.create! valid_attributes
        patch mailer_url(mailer), params: { mailer: new_attributes }
        mailer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mailer" do
        mailer = Mailer.create! valid_attributes
        patch mailer_url(mailer), params: { mailer: new_attributes }
        mailer.reload
        expect(response).to redirect_to(mailer_url(mailer))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mailer = Mailer.create! valid_attributes
        patch mailer_url(mailer), params: { mailer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mailer" do
      mailer = Mailer.create! valid_attributes
      expect {
        delete mailer_url(mailer)
      }.to change(Mailer, :count).by(-1)
    end

    it "redirects to the mailers list" do
      mailer = Mailer.create! valid_attributes
      delete mailer_url(mailer)
      expect(response).to redirect_to(mailers_url)
    end
  end
end
