default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 500

development:
  <<: *default
  database: profinder_dev
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: profinder_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres
